---

- name: Pip | Install
  apt: pkg=python-pip

- name: Virtualenv | Install
  pip: name=virtualenv

- name: Create virtualenv with requirements
  pip: name=flask virtualenv={{ item.path_virtualenv }}
  remote_user: "{{ user }}"
  with_items: "{{ flask_app }}"

- name: Activate the environment
  become: yes
  shell: . {{ item.path_virtualenv }}/bin/activate
  with_items: "{{ flask_app }}"

- name: Install app requirements
  pip:
    requirements={{ item.path_root }}/requirements.txt
  with_items: "{{ flask_app }}"

- name: Deploy gunicorn script
  template:
    src="run-gunicorn.sh.j2"
    dest="{{ item.path_root }}/run-gunicorn.sh"
    mode="0755"
  with_items: "{{ flask_app }}"
