---
- name: Virtualenv | Install
  apt: pkg=virtualenv

- name: Create virtualenv from flask app
  command: virtualenv env chdir=/home/vagrant/{{ flask_app_name }}

- name: Activate the environment
  become: yes
  shell: . /home/vagrant/{{ flask_app_name }}/  env/bin/activate

- name: Pip | Install
  apt: pkg=python-pip

- name: Flask | Install
  pip: name=flask

- name: Install flask app requirements
  pip: -r requirements.txt chdir=/home/vagrant/{{ flask_app_name }}

- name: Launch the flask app with gunicorn
  command: gunicorn -b {{ server_ip }} application:app --chdir /home/vagrant/{{ flask_app_name }}
...