---

- name: Pip | Install
  apt: pkg=python-pip

- name: Virtualenv | Install
  pip: name=virtualenv

- name: Create log folder
  file:
    dest: "{{ item.0.path_logs }}/{{ item.1 }}"
    state: directory
    mode: 0755
  with_nested:
    - "{{ flask_apps }}"
    - ['gunicorn','nginx','supervisor']

- name: Create virtualenv with requirements
  pip: name=flask virtualenv={{ item.path_virtualenv }}
  remote_user: "{{ user }}"
  with_items: "{{ flask_apps }}"

- name: Pip install requirements into virtualenv
  shell: . {{ item.path_virtualenv }}/bin/activate && {{ item.path_virtualenv }}/bin/pip install -r {{ item.path_root }}/requirements.txt
  args:
    chdir: "{{ item.path_root }}"
  become: true
  with_items: "{{ flask_apps }}"

- name: Deploy gunicorn script
  template:
    src="run-gunicorn.sh.j2"
    dest="{{ item.path_root }}/run-gunicorn.sh"
    mode="0755"
  with_items: "{{ flask_apps }}"
