---

- name: Pip | Install
  apt: pkg=python-pip

- name: Flask | Install
  pip: name=flask

- name: Virtualenv | Install
  pip: name=virtualenv

- name: Create virtualenv with requirements
  pip: name=flask virtualenv=/home/{{ user }}/{{ flask_app_name }}/env
  remote_user: "{{ user }}"

- name: Activate the environment
  become: yes
  shell: . /home/{{ user }}/{{ flask_app_name }}/env/bin/activate




