- name: Nginx | Install
  apt: pkg=nginx state=latest
  register: installed

- name:  Nginx | Remove the default app
  file: path=/etc/nginx/sites-enabled/default state=absent
  when: installed.changed

- name: Nginx | Remove apps symlinks
  file: path=/etc/nginx/sites-enabled/{{ item.name }} state=absent
  with_items: "{{ nginx_apps }}"

- name: Nginx | Configure
  template:
    src=nginx_app.j2
    dest=/etc/nginx/sites-available/{{ flask_app_name }}

- name: Nginx | Enable app
  file: src=/etc/nginx/sites-available/{{ flask_app_name }} dest=/etc/nginx/sites-enabled/{{ flask_app_name }} state=link
  notify:
    - Restart Nginx
