---
- name: Install Nginx, SQlite, Supervisord, Gunicorn, Python
  hosts: all
  remote_user: root

  roles:
    - role: nginx
    - role: sqlite
    - role: supervisord
    - role: gunicorn

- name: Install python (with pip and flask) and deploy the hello world app
  hosts: all
  remote_user: root
  
  roles:
    - role: flask
