---
- name: Install Nginx, SQlite, Supervisord, Gunicorn, flask and deploy the app
  hosts: all
  remote_user: root
  vars:
    user: vagrant
    flask_app_name: helloWorldApp

  roles:
    - role: nginx
    - role: sqlite
    - role: supervisord
    - role: gunicorn
    - role: flask

