---
- name: Install
  apt: pkg=supervisor state=present

- name: Create group
  group: name=supervisord system=yes state=present

- name: Configure
  template:
    src=supervisord.conf.j2
    dest={{ supervisord_include_path }}/{{ item.name }}.conf
  with_items: "{{ supervisord_apps }}"
  register: supervisord_config_file

- name: Restart supervisord if the config task has changes
  service: name=supervisor state=restarted
  when: supervisord_config_file.changed

- name: Start supervisord
  service: name=supervisor state=started enabled=yes
